---
name: Plugin-compiler build

on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed

env:
  GOLANG_CROSS: 1.19-bullseye

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.verify-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup node to match github-script v6 node runtime
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: install dependency
        run: npm install semver

      - name: Verify whether valid semver tag
        id: verify-tag
        uses: actions/github-script@v6
        with:
          script: |
            const semver = require('semver')
            let tag = semver.valid(context.payload.workflow_run.head_branch)
            return 'v'+tag
          result-encoding: string

      - name: Set docker metadata
        id: set-metadata
        uses: docker/metadata-action@v4
        with:
          images: asutoshjg/tyk-plugin-compiler
          labels: |
            org.opencontainers.image.title=tyk-plugin-compiler
            org.opencontainers.image.version=${{ steps.verify-tag.outputs.tag }}
            org.opencontainers.image.description=Plugin compiler for the Tyk API Gateway
          tags: |
            type=semver,pattern=v{{version}},value=${{ steps.verify-tag.outputs.tag }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ steps.verify-tag.outputs.tag }}


      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ci/images/plugin-compiler/Dockerfile
          platforms: linux/amd64
          push: ${{ steps.verify-tag.outputs.tag != '' }}
          labels: ${{ steps.set-metadata.outputs.labels }}
          tags: ${{ steps.set-metadata.outputs.tags }}
          build-args: |
            BASE-IMAGE=tykio/golang-cross:${{ env.GOLANG_CROSS }}
            GITHUB_SHA=${{ github.event.workflow_run.head_sha }}
            GITHUB_TAG=${{ steps.verify-tag.outputs.tag }}

  smoke-tests:
    needs:
      - docker-build
    if: ${{ needs.docker-build.outputs.tag != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Run test
        shell: bash
        run: |
          set -eaxo pipefail
          cd ci/tests/plugin-compiler
          ./test.sh ${{ needs.docker-build.outputs.tag }}
